default:
  image: node:16.20.2-buster

stages:
  - test

testeslint-job:
  stage: test
  script:
    - npm install
    - npx eslint .
  only:
    - main

locust-job:
  image: debian:latest
  stage: test
  script:
    - python -m ensurepip --upgrade
    - pip3 install locust
    - locust --headless --users 100 --spawn-rate 20 -H https://morningnews.obadasoussachaddad.fr/ -t 5s --only-summary
