
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTmlDMWJYWmxXRkl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeU1UTXhNRE0xTWpCYUZ3MHpOREF5TVRBeE1EUXdNakJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUREa0E3SG5BOWpmdWwvcWtFUGtMcmh4QkdWYzlaR2hqeFZ5Ly9KeUtlY1d1MldlMmcrZEk4eXZDVEUKay9yRXRFaE1CWHVoRTFlbFRZeVFySFVCRU1zS1JOV2dOOURzeEl5MGZKQWlNYWNXbHhtM0Q3K0ZFRUdFUzFZZwpNYkN0eHgwc2ppZ2tyenE3UEJiczI1dGVRZy81YnMrMFNJOU42VjJ6STN6TjdSNHkvaTNlZ1dnR2hJN2pwRGljCkN4dTlUYnI3cjN0U1ZlVjRUSXpKeVhzMEVseis1dGlHUkVJWHluL2Y2YjgzZ3hBaTRKcjNMc2ZUQlZPR3JSZVQKS202RjZ1TFVkaVJySG5xYzg4dXBtSGtlYTZ3MVI1ZVVqZ0h5S0g3Uy80T0tzZlluVjRSZ3NKT3NFaGErQ1B5UAo2RHd6bUs0b3RHanQ3a2Jibmp3MWM1Q0ZVMG85QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUeTNmaTJsbHJpMlVqMGtVa0tORDZpUkdEOWdUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWRjayt4YndYTwoweGRNVjF4TVJhYUNjQkE1cDN5UGhKODZncG40R1JWei8reHlMYlRhcHdIN0J3MVNrYnhYVXFKQVlUK2QzQ1pqCkY2VjQ1VkJaNTM3NHJKd0NMenlXQVVWL1A0aFRjdFVQR2pKSktWY1RzZTRRY0Q5eTJFdWxWbS9MTUpLZnBhTGkKRDBHVk1CL09oOHF4SEhVYnpzenhjN3RJNlpRN3VpKy9ncnBhaDlHT0FxdU1aZCtqQ3JCMnRsMWgzekc5a28zbAo1dFRJM1pYWFZFRUZ3VFAvZXFQZ3VnSC9NcEFLcWMzTHVoMkJXZFZKVlV0QW5VTjQwZFVkeEFTWTlWOGQxdDhmCnpJamxhRStBOTd5eHpQZnQ4eWZlMkdmcmJXQ1hjWUIwOGxtcTJzZXZaMnRPQW1HNGR3YWdpclY4RHhnamtYazUKVmJZQmhwemNtMGVhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://263425e2-eea7-44d9-bdd3-fdd14ba4ad51.fr-par-1.linodelke.net:443
  name: lke156282

users:
- name: lke156282-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjRYcGpqSW1MVkt4QmJiOVphTFhMbzVST0RCQUt2dU9PNzFxWUd0TGZCYmsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4td3JwNmwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTQ0NmE3MmYtZWJiMC00ZGY3LWExNTktY2ViZDJmMzQ1OWY1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.Dk3bvdSV1_qkzIbTpr-XDdVuYtI2GJxobenlpCR5ieEmLWl0s3CEfwcI-Yjditw8Wa_bg52OfhiMmkhO7ldOTOdOUf1RLO3LFIBYzLqu8pr156gw2_Y7blGop7qax2GnGqH2yLuRlcpBRpz_Lu6mW4eWCp7RZ811F14MK2Zk5O2ioiUD-GA8jGYFeod_pFaoZpCZmSBKAZdUgrxu5zMn4RNKrhcsdNEuHA1SQgdXPfBD86R6sqenJEP-LQVvJhjX2nZNPLbdD_Cn7o3gP4TdxgM9iymbZp7oXeDU_Y1mue0Qlgg7z6Iszxh_x9umxgEDsxApX3df5gYNappk2WFVQA

contexts:
- context:
    cluster: lke156282
    namespace: default
    user: lke156282-admin
  name: lke156282-ctx

current-context: lke156282-ctx
