apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ1NJUTBZbU9JT0V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeU1UTXhOREV5TXpCYUZ3MHpOREF5TVRBeE5ERTNNekJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN4QVZGUnFzdlNUN2d3Nm1DRFlud2xYNW9ZOExOdy96aDgwRGhUR3FXTEJiWEh5QjFCZnF4YUxRK2kKbVlKbE0rcVlrREFJZWdYQTU2OUM0RWcrckp2UDdmS3lSdkk2K2QzdzExbkJpbVFTV1NaUnBnQ25HMnFmSyt0MgpiWnV0MWlsRTJQRkhrL3l5bGpIcndKZHNPZWMxWEduTjAvQXhwTjR6ZlNlMHU5Y2NuOENMZWRMQVFxQnlid0hqCmJFeGZzVnlhR3hXbFJlSThOU1AyaUNhVzlFcjBvbUVOUENPT0cyTlQ5T0ZROStNenNYQWRkMEJvNjhnWUpOdVkKMGoyVnNvV08wazBObjVJMzhaSUJIaU5wOEE5OXhPSzNpK25tbFpmU2x5d2pMbGJtcEdnUkRmODZoSDkzbnAzQwpRVjZWQ1YwQ1g1T1Y0REJadlE0a1F5TUZYaWt4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUN3NZS1ZCWm9EZlArdUV6THpLMlZ4VzJ1MlpEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlpGd0hRaHZTVgpFZUpMTkp0Ulg2UDhXQWk4Zkx5UFVhNFZLNGhkSm94NzIzaEZQRmh2TjZ5SjhnbmJ5amxvaTA4TnhEc1NQWlBrCmpJN2ZVMkNpV3hkT1RkQXY4MzlBQ1JZY0lrdXRKKzRrNS9EYWp2NDJaVG9VUDhtVlBiVGhpOUZOUW5xcEtyNjIKcDZZWU41QmxIMWNQRms5d0ZtaDU2dzd6THZ0bUJEazdaeHc5VVdwMkFEVUprZDlwRHhXUXhvRUlPa3RBRm5yRQp1TWJWVUNTR2NnSlNDY2Rxd2ZwM1J0ZEZsNkVXaTFFWjZpakZhanlOL0o2V1RHQloxVkQrazlhZHhjN1lHa3h3CnpBQ0JnSlV4cjZtNjhSdUhjMkxhdmw0ZGc0a253Ry8wZWxnV21BQW10bUhJT2V1bHFkQml3U0xrcC9qd3ZPd2QKRzFBMFl1aGNCcXpLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://839be383-59a2-4bf8-89b0-5886e7d7caac.fr-par-1.linodelke.net:443
    name: lke156312

users:
  - name: lke156312-admin
    user:
      as-user-extra: {}
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImRwcXhfVGJxdGhzNTJkWm5TNXhlY0d0V2J4NFZpSHhmblEzNnVkYWJORzQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tN2pyNmwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTVmNjVjODUtZTM2Ny00ZWQyLThiNjMtNThkNzgxNTA0NzQzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.H3TDzckU4MaDZHdQGWmFB9INbFDOiAVzRc-T6IDuWQ4bwbLgpw1ez-CTNTqU1rt7CNOYKsZUnIYvPs4y276eZFTLzLhFbI_s-zL9dgPBfz4Ctf8dQc8YoVQi921z5Rb19ibdv0IR7yY1fZPtE8jtulqiR2lc0u_nAJJ0C8cGhPPyYKv2pktmIHyBYKsdAjYPTQKHG93EuqB-YsctCaVB5ekXrOfk9ZdxVdwgCh3Rf59aosPlKyhZYh-K_4tfYkp2FUeL7nD5xfv-phF1wb7EdHDkSmLG_NRaMDR7q8eeZ4Eo1nlaqz40pQwAyAp-A6ynbWaiHVFROc_H_lynLQYK8A

contexts:
  - context:
      cluster: lke156312
      namespace: default
      user: lke156312-admin
    name: lke156312-ctx

current-context: lke156312-ctx
